


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import AuthProvider from "../provider/auh-provider";
// import InitDb from '@/Components/init-db';
import InitClient from "@/Components/InitClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        {/* <InitDb /> */}
        <InitClient/>
        <Navbar/>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
